# Generated by Django 2.1.3 on 2018-11-29 12:40

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', sorl.thumbnail.fields.ImageField(upload_to='thumbnails')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(default=111, upload_to='thumbnails'),
            preserve_default=False,
        ),
    ]
