# Generated by Django 2.1.3 on 2018-11-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181130_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
    ]
