# Generated by Django 2.1.3 on 2018-11-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.AddField(
            model_name='article',
            name='position',
            field=models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Article'), (3, 'Header')], default=1),
        ),
    ]
